apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-operator
  namespace: confluent
  labels:
    app.kubernetes.io/name: confluent-for-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: confluent-for-kubernetes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: confluent-for-kubernetes
    spec:
      serviceAccountName: confluent-for-kubernetes
      containers:
        - name: confluent-operator
          image: docker.io/confluentinc/confluent-operator:0.921.2
          imagePullPolicy: IfNotPresent
          args:
            - --debug=false
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODENAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30
